### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ansalaza** [isovic/graphmap#20]
Ran into the following error during the installation procedure:

```
mkdir -p obj_linux/codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/
g++ -static-libgcc -static-libstdc++ -D__cplusplus=201103L -I"./src/" -I"/usr/include/" -I"codebase/seqlib/src/libs/seqan-library-2.0.1/include" -I"codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/" -Icodebase/argumentparser/src -Icodebase/seqlib/src -DRELEASE_VERSION -O3 -fdata-sections -ffunction-sections -c -fmessage-length=0 -ffreestanding -fopenmp -m64 -std=c++11 -Werror=return-type -pthread  -o obj_linux/codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.o codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.cpp
In file included from codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/divsufsort_private.h:69:0,
                 from codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.cpp:29:
codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.cpp: In function 'saint_t sufcheck64(const sauchar_t*, const saidx64_t*, saidx64_t, saint_t)':
codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/divsufsort64.h:61:23: error: expected ')' before 'PRId64'
 #define PRIdSAIDX64_T PRId64
                       ^
codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/divsufsort_private.h:75:23: note: in expansion of macro 'PRIdSAIDX64_T'
 #  define PRIdSAIDX_T PRIdSAIDX64_T
                       ^
codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.cpp:185:49: note: in expansion of macro 'PRIdSAIDX_T'
         fprintf(stderr, "Out of the range [0,%" PRIdSAIDX_T "].\n"
                                                 ^
codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/divsufsort64.h:61:23: error: expected ')' before 'PRId64'
 #define PRIdSAIDX64_T PRId64
                       ^
codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/divsufsort_private.h:75:23: note: in expansion of macro 'PRIdSAIDX64_T'
 #  define PRIdSAIDX_T PRIdSAIDX64_T
                       ^
codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.cpp:198:36: note: in expansion of macro 'PRIdSAIDX_T'
                         "  T[SA[%" PRIdSAIDX_T "]=%" PRIdSAIDX_T "]=%d"
                                    ^
codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/divsufsort64.h:61:23: error: expected ')' before 'PRId64'
 #define PRIdSAIDX64_T PRId64
                       ^
codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/divsufsort_private.h:75:23: note: in expansion of macro 'PRIdSAIDX64_T'
 #  define PRIdSAIDX_T PRIdSAIDX64_T
                       ^
codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.cpp:229:34: note: in expansion of macro 'PRIdSAIDX_T'
                         "  SA[%" PRIdSAIDX_T "]=%" PRIdSAIDX_T " or\n"
                                  ^
make: *** [obj_linux/codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.o] Error 1
```
Any idea how to address it? Thanks!

**Comment by andreas-wilm** [comment]
Hey, could you please let us know which exact Graphmap version you are using, on which system (Mac, Linux etc) you are on and what the output for `g++ -v` is?

Thanks,
Andreas

**Comment by fritzsedlazeck** [comment]
Hi Andreas, 
I basically ran in the same problem. Just cloned the repo and followed installation (**__Current Version: 0.3.0__** ). 
I am on a Linux machine, gcc version 4.8.1 (GCC). I guess there is an error before that...

**Comment by isovic** [comment]
Hi,
compilation runs fine on Linux Mint 17.2 with GCC 4.8.4 on my end. Which distribution and version of Linux are you running, so I can try to reproduce the error?

Best regards,
Ivan.

**Comment by fritzsedlazeck** [comment]
Hi,
it is a Red Hat Enterprise Linux Server release 6.7 . I would be surprised if it is related to the Linux system. Usually those error indicate an error on compile before that position.... But I might be wrong.

Can it be related to seqlib? I cannot find the function: "codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.cpp: In function ‘saint_t sufcheck64"

I have also tried to use other version of gcc:

gcc version 4.9.3:
------------------------
mkdir -p obj_linux/codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/
g++ -static-libgcc -static-libstdc++ -D__cplusplus=201103L -I"./src/" -I"/usr/include/" -I"codebase/seqlib/src/libs/seqan-library-2.0.1/include" -I"codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/" -Icodebase/seqlib/src -Icodebase/argumentparser/src -DRELEASE_VERSION -O3 -fdata-sections -ffunction-sections -c -fmessage-length=0 -ffreestanding -fopenmp -m64 -std=c++11 -Werror=return-type -pthread  -o obj_linux/codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.o codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.cpp
In file included from codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/divsufsort_private.h:69:0,
                 from codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.cpp:29:
codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.cpp: In function ‘saint_t sufcheck64(const sauchar_t*, const saidx64_t*, saidx64_t, saint_t)’:
codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/divsufsort64.h:61:23: error: expected ‘)’ before ‘PRId64’
 #define PRIdSAIDX64_T PRId64
                       ^
...

gcc 4.7.2:
--------------
mkdir -p obj_linux/codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/
g++ -static-libgcc -static-libstdc++ -D__cplusplus=201103L -I"./src/" -I"/usr/include/" -I"codebase/seqlib/src/libs/seqan-library-2.0.1/include" -I"codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/" -Icodebase/seqlib/src -Icodebase/argumentparser/src -DRELEASE_VERSION -O3 -fdata-sections -ffunction-sections -c -fmessage-length=0 -ffreestanding -fopenmp -m64 -std=c++11 -Werror=return-type -pthread  -o obj_linux/codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.o codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.cpp
codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.cpp: In function ‘saint_t sufcheck64(const sauchar_t*, const saidx64_t*, saidx64_t, saint_t)’:
codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.cpp:185:49: error: expected ‘)’ before ‘PRId64’
codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.cpp:198:36: error: expected ‘)’ before ‘PRId64’
codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.cpp:229:34: error: expected ‘)’ before ‘PRId64’
make: *** [obj_linux/codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.o] Error 1


Thanks,
Fritz

**Comment by isovic** [comment]
Could you please try commenting out these lines and running make again?
https://github.com/isovic/seqlib/blob/6c00d87d8fa1012f815dcc5c547435ceb7485193/src/libs/libdivsufsort-2.0.1-64bit/utils.cpp#L184-L188
https://github.com/isovic/seqlib/blob/6c00d87d8fa1012f815dcc5c547435ceb7485193/src/libs/libdivsufsort-2.0.1-64bit/utils.cpp#L196-L201
https://github.com/isovic/seqlib/blob/6c00d87d8fa1012f815dcc5c547435ceb7485193/src/libs/libdivsufsort-2.0.1-64bit/utils.cpp#L227-L232

Additionally, I created a VM with fresh install of Fedora 23 Server because all servers at my disposal run Ubuntu/Debian. GraphMap compiled with no problems using GCC 5.3.1.

**Comment by fritzsedlazeck** [comment]
Sorry for the late response. It worked with commenting out those sections. 
Thanks
Fritz

**Comment by isovic** [comment]
The response was quite fast IMO :-)
Thanks for the report, I'll include the fix in the master branch and close the issue once it's done.

Best regards,
Ivan.

**Comment by isovic** [comment]
Fixed the master branch.
To use the latest version run:
```  
make modules  
make  
```

Best regards,
Ivan.

**Comment by ansalaza** [comment]
Still having issues with this.

Using a version I downloaded today (Current Version: 0.3.0).

CentOS Linux release 7.2.1511 with gcc version 4.8.5

After running:
```
make modules
make
```
I get the following (subset of stdout):

```
mkdir -p obj_linux/src/graphmap/
g++ -static-libgcc -static-libstdc++ -D__cplusplus=201103L -I"./src/" -I"/usr/include/" -I"codebase/seqlib/src/libs/seqan-library-2.0.1/include" -I"codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/" -Icodebase/argumentparser/src -Icodebase/seqlib/src -DRELEASE_VERSION -O3 -fdata-sections -ffunction-sections -c -fmessage-length=0 -ffreestanding -fopenmp -m64 -std=c++11 -Werror=return-type -pthread  -o obj_linux/src/graphmap/graphmap.o src/graphmap/graphmap.cc
mkdir -p obj_linux/src/graphmap/
g++ -static-libgcc -static-libstdc++ -D__cplusplus=201103L -I"./src/" -I"/usr/include/" -I"codebase/seqlib/src/libs/seqan-library-2.0.1/include" -I"codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/" -Icodebase/argumentparser/src -Icodebase/seqlib/src -DRELEASE_VERSION -O3 -fdata-sections -ffunction-sections -c -fmessage-length=0 -ffreestanding -fopenmp -m64 -std=c++11 -Werror=return-type -pthread  -o obj_linux/src/graphmap/core_graphmap.o src/graphmap/core_graphmap.cc
mkdir -p obj_linux/src/owler/
g++ -static-libgcc -static-libstdc++ -D__cplusplus=201103L -I"./src/" -I"/usr/include/" -I"codebase/seqlib/src/libs/seqan-library-2.0.1/include" -I"codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/" -Icodebase/argumentparser/src -Icodebase/seqlib/src -DRELEASE_VERSION -O3 -fdata-sections -ffunction-sections -c -fmessage-length=0 -ffreestanding -fopenmp -m64 -std=c++11 -Werror=return-type -pthread  -o obj_linux/src/owler/owler.o src/owler/owler.cc
mkdir -p obj_linux/src/owler/
g++ -static-libgcc -static-libstdc++ -D__cplusplus=201103L -I"./src/" -I"/usr/include/" -I"codebase/seqlib/src/libs/seqan-library-2.0.1/include" -I"codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/" -Icodebase/argumentparser/src -Icodebase/seqlib/src -DRELEASE_VERSION -O3 -fdata-sections -ffunction-sections -c -fmessage-length=0 -ffreestanding -fopenmp -m64 -std=c++11 -Werror=return-type -pthread  -o obj_linux/src/owler/process_read.o src/owler/process_read.cc
mkdir -p obj_linux/src/owler/
g++ -static-libgcc -static-libstdc++ -D__cplusplus=201103L -I"./src/" -I"/usr/include/" -I"codebase/seqlib/src/libs/seqan-library-2.0.1/include" -I"codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/" -Icodebase/argumentparser/src -Icodebase/seqlib/src -DRELEASE_VERSION -O3 -fdata-sections -ffunction-sections -c -fmessage-length=0 -ffreestanding -fopenmp -m64 -std=c++11 -Werror=return-type -pthread  -o obj_linux/src/owler/owler_experimental.o src/owler/owler_experimental.cc
mkdir -p obj_linux/src/owler/
g++ -static-libgcc -static-libstdc++ -D__cplusplus=201103L -I"./src/" -I"/usr/include/" -I"codebase/seqlib/src/libs/seqan-library-2.0.1/include" -I"codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/" -Icodebase/argumentparser/src -Icodebase/seqlib/src -DRELEASE_VERSION -O3 -fdata-sections -ffunction-sections -c -fmessage-length=0 -ffreestanding -fopenmp -m64 -std=c++11 -Werror=return-type -pthread  -o obj_linux/src/owler/owler_data.o src/owler/owler_data.cc
mkdir -p obj_linux/src/owler/
g++ -static-libgcc -static-libstdc++ -D__cplusplus=201103L -I"./src/" -I"/usr/include/" -I"codebase/seqlib/src/libs/seqan-library-2.0.1/include" -I"codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/" -Icodebase/argumentparser/src -Icodebase/seqlib/src -DRELEASE_VERSION -O3 -fdata-sections -ffunction-sections -c -fmessage-length=0 -ffreestanding -fopenmp -m64 -std=c++11 -Werror=return-type -pthread  -o obj_linux/src/owler/dpfilter.o src/owler/dpfilter.cc
mkdir -p obj_linux/src/
g++ -static-libgcc -static-libstdc++ -D__cplusplus=201103L -I"./src/" -I"/usr/include/" -I"codebase/seqlib/src/libs/seqan-library-2.0.1/include" -I"codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/" -Icodebase/argumentparser/src -Icodebase/seqlib/src -DRELEASE_VERSION -O3 -fdata-sections -ffunction-sections -c -fmessage-length=0 -ffreestanding -fopenmp -m64 -std=c++11 -Werror=return-type -pthread  -o obj_linux/src/program_parameters.o src/program_parameters.cc
mkdir -p obj_linux/src/
g++ -static-libgcc -static-libstdc++ -D__cplusplus=201103L -I"./src/" -I"/usr/include/" -I"codebase/seqlib/src/libs/seqan-library-2.0.1/include" -I"codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/" -Icodebase/argumentparser/src -Icodebase/seqlib/src -DRELEASE_VERSION -O3 -fdata-sections -ffunction-sections -c -fmessage-length=0 -ffreestanding -fopenmp -m64 -std=c++11 -Werror=return-type -pthread  -o obj_linux/src/main.o src/main.cc
mkdir -p ./bin/Linux-x64/
g++ -static-libgcc -static-libstdc++ -m64 -ffreestanding -L"/usr/local/lib" -L"codebase/seqlib/src/libs/libdivsufsort-2.0.1/build/lib" -o ./bin/Linux-x64/graphmap ./obj_linux/codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/utils.o ./obj_linux/codebase/seqlib/src/libs/edlib.o ./obj_linux/codebase/seqlib/src/libs/opal.o ./obj_linux/codebase/argumentparser/src/example.o ./obj_linux/codebase/argumentparser/src/argparser.o ./obj_linux/codebase/seqlib/src/test.o ./obj_linux/codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/sssort.o ./obj_linux/codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/trsort.o ./obj_linux/codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/divsufsort.o ./obj_linux/codebase/seqlib/src/utility/utility_general.o ./obj_linux/codebase/seqlib/src/utility/evalue_constants.o ./obj_linux/codebase/seqlib/src/utility/evalue.o ./obj_linux/codebase/seqlib/src/sequences/sequence_gfa_test.o ./obj_linux/codebase/seqlib/src/sequences/sequence_file.o ./obj_linux/codebase/seqlib/src/sequences/sequence_alignment.o ./obj_linux/codebase/seqlib/src/sequences/sequence_gfa.o ./obj_linux/codebase/seqlib/src/sequences/sequence_alignment_test.o ./obj_linux/codebase/seqlib/src/sequences/single_sequence.o ./obj_linux/codebase/seqlib/src/log_system/log_system.o ./obj_linux/src/alignment/alignment.o ./obj_linux/src/alignment/semiglobal.o ./obj_linux/src/alignment/cigargen.o ./obj_linux/src/alignment/anchored.o ./obj_linux/src/alignment/alignment_wrappers.o ./obj_linux/src/index/index_spaced_hash_fast.o ./obj_linux/src/index/index_owler.o ./obj_linux/src/index/index.o ./obj_linux/src/index/index_spaced_hash.o ./obj_linux/src/index/index_sa.o ./obj_linux/src/index/index_hash.o ./obj_linux/src/containers/path_graph_entry.o ./obj_linux/src/containers/mapping_data.o ./obj_linux/src/containers/vertices.o ./obj_linux/src/containers/region.o ./obj_linux/src/containers/score_registry.o ./obj_linux/src/graphmap/experimental.o ./obj_linux/src/graphmap/lcs_anchored.o ./obj_linux/src/graphmap/region_selection.o ./obj_linux/src/graphmap/process_read.o ./obj_linux/src/graphmap/lcs_semiglobal.o ./obj_linux/src/graphmap/filter_anchors.o ./obj_linux/src/graphmap/graphmap.o ./obj_linux/src/graphmap/core_graphmap.o ./obj_linux/src/owler/owler.o ./obj_linux/src/owler/process_read.o ./obj_linux/src/owler/owler_experimental.o ./obj_linux/src/owler/owler_data.o ./obj_linux/src/owler/dpfilter.o ./obj_linux/src/program_parameters.o ./obj_linux/src/main.o -lpthread -lgomp -lm -lz
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make: *** [linux] Error 1

```

**Comment by andreas-wilm** [comment]
Hello, could it be that libstdc++ is not installed (not sure what the
actual package is called). Andreas

**Comment by ansalaza** [comment]
Thanks Andreas.

It turns out that the issue was that it was trying to build with static linking and libstd++ is dynamically linked to other libraries.

I removed the static calls in the Makefile and it successfully installed and appears to be running without any issues. Below are the changes I made to the Makefile.

```
#CC_LIBS = -static-libgcc -static-libstdc++ -D__cplusplus=201103L
CC_LIBS = -D__cplusplus=201103L

#LD_FLAGS = -static-libgcc -static-libstdc++ -m64 -ffreestanding
LD_FLAGS = -m64 -ffreestanding

```

**Comment by andreas-wilm** [comment]
Good catch.

Maybe moving to a full blown automake setup would make sense for Graphmap
to allow easier handling of all these different options.

Andreas
